In [1]:
# lecture: https://carmengg.github.io/eds-220-book/lectures/lesson-1-python-review.html


# Numpy

- one of the core packages for numerical computing in Python
- many packages are built on top of numpy
- `numpy` has been optimized for processing: faster due to memory access

In [2]:
# import numpy with standard abbreviation
import numpy as np



# Variables

we can think about variables as a name we assign to a particular object in Python. For example:

In [3]:
# assign a small array to a variable s

a = np.array([ [1,1,2], [3,5,8] ])

When we run the cell, we store the variable and its value. We can see the variable's value in two ways:

In [6]:
# show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [7]:
# print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Naming variables
in this class, we'll use `snake_case` for naming variables.

# Variables and objects

**object**: often encountered in Python documentation and tutorials.

object is a bundle of properties and actions about something specific

Example:

- object: data frame
- properties: number of rows, names of columns, date created
- actions: selecting a row, addign a new column, etc. ...


A variable is a name we give a specific object, and the same object can be referenced by different variables.


Example:

- The Sun (actual star at the center of the solar system) = object
- sol (Spanish word for Sun) = variable
- soleil (French for Sun) = another variable


In Practice: we will use object and variable interchangeably 



# Types


Each object in Python has a type.

type = what kind of object it is

We can also call the type of the object, the **class** of the object. 

We can see the type/class of an object by using the `type` function.

In [8]:
print(a)

[[1 1 2]
 [3 5 8]]


In [9]:
type(a)

numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy pakcage. We can check the type of an entry in the array by indexing:

In [10]:
print(a[0,0])
type(a[0,0])

1


numpy.int64

Notice the type of the value 1 in the array is `numpy.int64` and not just the core Python integer type `int`. The NumPy type `numpy.int64` is telling us 1 is an integer stored as a 64-bit number. NumPy has its own data types to deal with numbers depending on memory storage and floating point precision: https://numpy.org/doc/stable/reference/arrays.scalars.html#sized-aliases

Since “everything in Python is an object” and every object has a class, we will interact with SO MANY classes in this course. Often, knowing the type of an object is the first step to finding information to code what you want!

In [11]:
# acccess the value 5 in array a:

print(a[1,1])

5


In [12]:
a[1,1]

5

In [13]:
a[1][1]

5

# Functions


`print` was our first example of a Python function!  :)

A function:
- take in a set of **arguments**, separated by commas, and
- use those arguments to create some **output**.


We can use "argument" and "parameter" interchangeably (in this class, at least)


We can ask for information about a function by executing ? followed by the function name:

In [14]:
?print

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


- The first line is always the function showing all of its arguments in parenthesis. 
- Then there is a short description of what the function does. And finally a list of the arguments and a brief explanation about each of them.

You can see there are different types of arguments inside the parenthesis. Roughly speaking, a function has two types of arguments:

- **non-optional arguments:** arguments you need to specify for the function to do something, and

- **optional arguments:** arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`.

Example:

`end` is an argument in `print` with the default value a new line. We can change this argument so that finishes the line with `^_^` instead:

In [16]:
# notice we had always used print withough specifying any value for the `end` argument
print('I am changing the default end argument of the print function', end=' ^_^')

I am changing the default end argument of the print function ^_^

### Attributes & Methods

An object in Python has attributes and methods. 

- **attribute**: a property of the object, some piece of information about it. 
- **method**: a procedure associated with an object, an action where the main ingredient is the object.

Cat example:

attributes:
- name
- color
- age
- weight

methods:
- meow()
- nap()
- chase_laser()
- move_tail()

Fish:
Attributes:
- scale_color
- weight
- age
- sex
- species

Methods:
- swim()
- eat()
- poop()
- jump_out_of_water()


More formally, a method is a function that acts on the object it is part of.

We can access a variable’s attributes and methods by adding a period . at the end of the variable’s name. So we would write 

`variable.variable_method()` or

`variable.variable_attribute`.


Examples:

Methods and attributes of NumPy arrays:

In [1]:
import numpy as np

In [2]:
# define a 3x3 array

var = np.array( [ [1,2,3],[4,5,6],[7,8,9] ] )

In [3]:
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# shape: attribute telling us the number of elements
# in each dimension of the array

var.shape

(3, 3)

In [5]:
type(var.shape)

tuple

In [8]:
# ndim is an attribute holding the number of array dimensions
print(var.ndim)

2


In [9]:
type(var.ndim)

int

- Notice attributes can have many different data types.


Examples of methods:

In [10]:
# min method for an array
# return the minimum value in the array

var.min()

1

In [11]:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [12]:
type(var.min())

numpy.int64

In [13]:
type(var.min)

builtin_function_or_method

In [14]:
var.min(axis=0)

array([1, 2, 3])

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

## R & Python

R doesn't use methods within an object. Functions are extrinsic to the objects they are acting on. 

Ex:
In R, for example, there would be two separate items: the variable `var` and a separate function `min` that gets `var` as a parameter:
```
# this is R code

var <- array(c(1,4,7,2,5,8,3,6,9), dim =c(3,3))
min(var)
```

Using the pipe operator %>% in R’s tidyverse is closer to the dot `.` in Python:

```
# this is R code

var <- array(c(1,4,7,2,5,8,3,6,9), dim =c(3,3))
var %>% min()

```
What happens here is that the pipe `%>%` is passing `var` to the `min()` function as its first argument. This is essentially what happens in Python when a function is a method of a class (what the `.` is in Python):

```
# this is Python code

var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var.min()
```
When working in Python, remember that *methods are functions that are part of an object* and a method uses the object it is part of to produce some information.